### ISSUE TITLE
On windows notes can sometimes not be deleted

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/uwuNote#3]
Throws a `File is in use error`

**Comment by Bios-Marcel** [comment]
Attempt to fix with 63cd2f77dfe722ab20b0e8ab5726eb5043145553

**Comment by MarvinKlar** [comment]
I can't reproduce this bug with the changes of https://github.com/Bios-Marcel/uwuNote/commit/63cd2f77dfe722ab20b0e8ab5726eb5043145553
